### PR TITLE
Set up docker-compose for dev

### PR DESCRIPTION
**Pull request by spraints**
This should simplify setting everything up for the team. @ocawesome101 can install docker using his package manager (or keep running things locally). Everyone else can install [Docker Desktop](https://www.docker.com/products/docker-desktop). On macOS, open a command prompt in the app's directory and run `script/bootstrap`. On Windows, open a command prompt in the app's directory and run `docker-compose pull`, `docker-compose build`, `docker-compose up -d`, then wait a few seconds, and `docker-compose run --rm app migrate`.

The app will be visible at http://127.0.0.1:8080/. A database admin tool will be available at http://127.0.0.1:9080/ (login as "postgres" / "password").

cc @Ocawesome101

### CODE REVIEW

**Comment by spraints** [comment]
Note: this doesn't work correctly yet, the app can't connect to the database for some reason.

**Comment by spraints** [comment]
I'm pretty sure this is working now.

**Comment by spraints** [comment]
To use:

1. Install docker.
1. Check out this branch.
    1. `git remote add spraints https://github.com/spraints/fitness-tracker-backend`
    2. `git fetch spraints`
    3. `git checkout -b docker-ify spraints/docker-ify`)
1. Set up the app. (`script/bootstrap`)
1. Run it. (`docker-compose up`)
1. Use the app. (http://127.0.0.1:8080)
1. Check out the database. (http://127.0.0.1:9080, log in as "postgres" / "password" with database="hot_dog_fitness_development")

**Comment by Ocawesome101** [comment]
ok

**Pull request merged**
